CREATE USER prgmgtest IDENTIFIED BY 12345;

GRANT CREATE SESSION TO prgmgtest;
GRANT CREATE DATABASE LINK TO prgmgtest;
GRANT CREATE MATERIALIZED VIEW TO prgmgtest;
GRANT CREATE PROCEDURE TO prgmgtest;
GRANT CREATE PUBLIC SYNONYM TO prgmgtest;
GRANT CREATE ROLE TO prgmgtest;
GRANT CREATE SEQUENCE TO prgmgtest;
GRANT CREATE SYNONYM TO prgmgtest;
GRANT CREATE TABLE TO prgmgtest;
GRANT DROP ANY TABLE TO prgmgtest;
GRANT CREATE TRIGGER TO prgmgtest;
GRANT CREATE TYPE TO prgmgtest;
GRANT CREATE VIEW TO prgmgtest;



CREATE TABLE FL_CODE
(
    PJT_COMM_C VARCHAR2(2)  NOT NULL,
    PJT_DESC_C VARCHAR2(50) NOT NULL,
    PJT_YN_C   VARCHAR2(1)  NOT NULL,
    CONSTRAINT PK_CODE PRIMARY KEY (PJT_COMM_C)
);
CREATE TABLE FL_EMP_CODE
(
    PJT_DEPT_C    VARCHAR2(3) NOT NULL,
    PJT_LV_C      VARCHAR2(3) NOT NULL,
    PJT_EMP_DIV_C VARCHAR2(3) NOT NULL,
    PJT_POS_C     VARCHAR2(3) NOT NULL,
    PJT_JG_C      VARCHAR2(3) NOT NULL,
    PJT_DUTY_C    VARCHAR2(3) NOT NULL,
    CONSTRAINT PK_EMP_CODE PRIMARY KEY (PJT_LV_C, PJT_EMP_DIV_C, PJT_POS_C, PJT_JG_C, PJT_DUTY_C)
);

CREATE TABLE FL_PJT_CODE
(
    PJT_C     VARCHAR2(8) NOT NULL,
    PJT_DIV_C VARCHAR2(3) NOT NULL,
    PJT_ST_C  VARCHAR2(3) NOT NULL,
    PJT_ORG_C VARCHAR2(3) NOT NULL,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (PJT_C, PJT_DIV_C, PJT_ST_C, PJT_ORG_C)
);
CREATE TABLE FL_EMP
(
    EMP_NO        VARCHAR2(7)  NOT NULL,
    EMP_NM        VARCHAR2(10) NOT NULL,
    EMP_PW        VARCHAR2(15) NOT NULL,
    EMP_EMAIL     VARCHAR2(30) NOT NULL,
    PJT_EMP_DIV_C VARCHAR2(3)  NOT NULL,
    PJT_JG_C      VARCHAR2(3)  NOT NULL,
    EMP_PHONE_NO  VARCHAR2(15) NOT NULL,
    EMP_EMER_NO   VARCHAR2(15) NOT NULL,
    EMP_JOIN_DATE VARCHAR2(10) NOT NULL,
    PJT_DEPT_C    VARCHAR2(10) NOT NULL,
    PJT_LV_C      VARCHAR2(3)  NOT NULL,
    PJT_POS_C     VARCHAR2(3)  NOT NULL,
    PJT_DUTY_C    VARCHAR2(3)  NOT NULL,
    CONSTRAINT PK_EMP
        PRIMARY KEY (EMP_NO, EMP_EMAIL),
    CONSTRAINT FK_EMP
        FOREIGN KEY (PJT_LV_C, PJT_POS_C, PJT_DUTY_C, PJT_JG_C, PJT_EMP_DIV_C)
            REFERENCES FL_EMP_CODE (PJT_LV_C, PJT_POS_C, PJT_DUTY_C, PJT_JG_C, PJT_EMP_DIV_C)
);

CREATE TABLE FL_EMP_ADMIN
(
    EMP_NO            VARCHAR2(7)               NOT NULL,
    LOGIN_DATE        TIMESTAMP DEFAULT SYSDATE NOT NULL,
    JOIN_DATE         TIMESTAMP DEFAULT SYSDATE NOT NULL,
    US_CHANGE_PW_DATE VARCHAR2(10),
    LOGIN_FAIL_COUNT  NUMBER,
    LIST_ACCESS_DATE  VARCHAR2(10),
    CONSTRAINT PK_EMP_ADMIN PRIMARY KEY (EMP_NO)
);

CREATE TABLE FL_PROJECT
(
    PJT_C          VARCHAR2(11) NOT NULL,
    PJT_ORG_C      VARCHAR2(3)  NOT NULL,
    PJT_DIV_C      VARCHAR2(3)  NOT NULL,
    PJT_ST_C       VARCHAR2(3)  NOT NULL,
    PJT_CLIENT     VARCHAR2(50) NOT NULL,
    PJT_NM         VARCHAR2(50) NOT NULL,
    PJT_EMP_LIST   VARCHAR2(80) NOT NULL,
    PJT_PM         VARCHAR2(10) NOT NULL,
    PJT_START_DATE VARCHAR2(10) NOT NULL,
    PJT_END_DATE   VARCHAR2(10) not null,
    PJT_END_YN     VARCHAR2(1)  not null,
    CONSTRAINT PK_FL_PROJECT PRIMARY KEY (PJT_C),
    CONSTRAINT FK_FL_PROJECT FOREIGN KEY (PJT_C, PJT_ORG_C, PJT_DIV_C, PJT_ST_C)
        REFERENCES FL_PJT_CODE (PJT_C, PJT_ORG_C, PJT_DIV_C, PJT_ST_C)
);


CREATE TABLE FL_PJT_EMP_ADMIN
(
    PJT_C         VARCHAR2(11) NOT NULL
        CONSTRAINT PK_PJT_EMP_ADMIN
            PRIMARY KEY,
    EMP_NO        VARCHAR2(7)  NOT NULL,
    PJT_EMP_DIV_C VARCHAR2(3)  NOT NULL,
    EMP_NM        VARCHAR2(10) NOT NULL,
    EMP_EMAIL     VARCHAR2(30) NOT NULL,
    PJT_DIV_C     VARCHAR2(3)  NOT NULL,
    PJT_ST_C      VARCHAR2(3)  NOT NULL,
    PJT_CMT_START VARCHAR2(10) NOT NULL,
    PJT_CMT_PD    VARCHAR2(8)  NOT NULL,
    PJT_JG_C      VARCHAR2(3)  NOT NULL,
    PJT_ORG_C     VARCHAR2(3)  NOT NULL,
    CONSTRAINT FK_PJT_EMP_ADMIN_01
        FOREIGN KEY (EMP_NO, EMP_NM, EMP_EMAIL, PJT_EMP_DIV_C, PJT_JG_C) REFERENCES FL_EMP,
    CONSTRAINT FK_PJT_EMP_ADMIN_02
        FOREIGN KEY (PJT_C, PJT_DIV_C, PJT_ST_C, PJT_ORG_C) REFERENCES FL_PJT_CODE
);

