CREATE TABLE FL_CODE
(
    PJT_COMM_C VARCHAR2(2)  NOT NULL,
    PJT_DESC_C VARCHAR2(50) NOT NULL,
    PJT_YN_C   VARCHAR2(1)  NOT NULL,
    CONSTRAINT PK_CODE PRIMARY KEY (PJT_COMM_C)
);
CREATE TABLE FL_EMP_CODE
(
    PJT_DEPT_C    VARCHAR2(3) NOT NULL,
    PJT_LV_C      VARCHAR2(3) NOT NULL,
    PJT_EMP_DIV_C VARCHAR2(3) NOT NULL,
    PJT_POS_C     VARCHAR2(3) NOT NULL,
    PJT_JG_C      VARCHAR2(3) NOT NULL,
    PJT_DUTY_C    VARCHAR2(3) NOT NULL,
    CONSTRAINT PK_EMP_CODE PRIMARY KEY (PJT_LV_C, PJT_EMP_DIV_C,PJT_POS_C,PJT_JG_C,PJT_DUTY_C)
);
